const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
const LOGOUT_PROFILE = "LOGOUT_PROFILE";
const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export { SET_USER_PROFILE_DATA, LOGOUT_PROFILE, SET_PRODUCTS_LIST };
