const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
const LOGOUT_PROFILE = "LOGOUT_PROFILE";
const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
const ASYNC_ACTION = "ASYNC_ACTION";

export { SET_USER_PROFILE_DATA, LOGOUT_PROFILE, SET_PRODUCTS_LIST, ASYNC_ACTION };
