const SET_USER_PROFILE_DATA = "SET_USER_PROFILE_DATA";
const LOGOUT_PROFILE = "LOGOUT_PROFILE";
const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
const ASYNC_ACTION = "ASYNC_ACTION";
const DISPLAY_PRELOADER = "DISPLAY_PRELOADER";
const SET_CATALOG_FILTER_DATA = "SET_CATALOG_FILTER_DATA";
const RESET_CATALOG_FILTER_DATA = "RESET_CATALOG_FILTER_DATA";
const SET_SORT_VALUE = "SET_SORT_VALUE";
const SET_CART_DATA = "SET_CART_DATA";

export { SET_USER_PROFILE_DATA, LOGOUT_PROFILE, SET_PRODUCTS_LIST, ASYNC_ACTION, SET_CART_DATA };
export { DISPLAY_PRELOADER, SET_CATALOG_FILTER_DATA, RESET_CATALOG_FILTER_DATA, SET_SORT_VALUE };
